name: Deploy Function App

on:
  push:
    paths:
      - 'app/**'
      - 'infraestrutura/**'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
      resource_group: "my-resource-group"
      function_app_name: "my-function-app"
      terraform_directory: "infraestrutura/"
      app_directory: "app/"