name: Deploy Function App

on:
  push:
    paths:
      - 'app/**'
      - 'infraestrutura/**'
  workflow_dispatch:

jobs:
  deploy_app:
    if: ${{ github.event_name == 'push' && contains(github.event.head_commit.message, 'app/') }}
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      resource_group: "my-resource-group"
      function_app_name: "my-function-app"
      app_directory: "app/"
    secrets: inherit

  deploy_infra:
    if: ${{ github.event_name == 'push' && contains(github.event.head_commit.message, 'infraestrutura/') }}
    uses: ./.github/workflows/reusable-terraform.yml
    with:
      terraform_directory: "infraestrutura/"
    secrets: inherit