name: Deploy Function App

on:
  push:
    paths:
      - 'app/**'
  workflow_dispatch:

jobs:
  deploy_app:
    if: ${{ github.event_name == 'push' && contains(github.event.head_commit.message, 'app/') }}
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: HOM
      function_app_name: "my-function-app"
      app_directory: "app/"
      resource_group: "functionapp-dev-poc-rg"
    secrets: inherit
