# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App - poc-slot

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'app/' 
  NODE_VERSION: '22.x' 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Resolve Project Dependencies Using Npm'
        working-directory: './app'
        shell: bash
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        working-directory: './app'
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: app/release.zip

  deploy-slot-hom:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d app/

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_ECB54451D1D74ED9BCCD0828B36811FC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FECDFCAE7A11490C9A804F716780CBF2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BC90065897794AAB8AA280B24CEE7572 }}


      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'poc-slot'
          slot-name: 'hom'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

  deploy-prd:
    runs-on: ubuntu-latest
    needs: [deploy-slot-hom]
    permissions:
      id-token: write
      contents: read

    steps:

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_ECB54451D1D74ED9BCCD0828B36811FC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FECDFCAE7A11490C9A804F716780CBF2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BC90065897794AAB8AA280B24CEE7572 }}

      - name: Swap Slots (hom -> production)
        if: ${{ success() }}
        run: |
          az functionapp deployment slot swap \
            --name 'poc-slot' \
            --resource-group 'pocslot' \
            --slot 'hom' \
            --target-slot 'production'