name: Reusable Deploy Workflow

on:
  workflow_call:
    inputs:
      resource_group:
        required: true
        type: string
      function_app_name:
        required: true
        type: string
      app_directory:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy Function App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install Dependencies
        run: |
          cd ${{ inputs.app_directory }}
          npm install

      - name: Build Application
        run: |
          cd ${{ inputs.app_directory }}
          npm run build

      - name: Verify Storage Account Access
        run: |
          az storage account show \
            --name "storageaccountdevpoc" \
            --resource-group ${{ inputs.resource_group }}

      - name: Create ZIP File
        run: |
          cd ${{ inputs.app_directory }}
          mkdir -p dist
          zip -r dist/app.zip .

      - name: Deploy to Staging Slot
        run: |
          az functionapp deployment source config-zip \
            --resource-group ${{ inputs.resource_group }} \
            --name ${{ inputs.function_app_name }} \
            --slot staging \
            --src ${{ inputs.app_directory }}/dist/app.zip
  
      - name: Swap Staging to Production
        run: |
          az functionapp deployment slot swap \
            --resource-group ${{ inputs.resource_group }} \
            --name ${{ inputs.function_app_name }} \
            --slot staging